//
// Generated file, do not edit! Created by opp_msgtool 6.4 from src/LifesatPackets.msg.
//

#ifndef __LIFESAT_LIFESATPACKETS_M_H
#define __LIFESAT_LIFESATPACKETS_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0604
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace lifesat {

class Telecommand;
class Telemetry;

}  // namespace lifesat

// cplusplus {{
#include "inet/common/INETDefs.h"
// }}


namespace lifesat {

/**
 * Enum generated from <tt>src/LifesatPackets.msg:23</tt> by opp_msgtool.
 * <pre>
 * //
 * // Satellite operating mode, a component of the logical state channel
 * //
 * enum SatMode
 * {
 *     MODE_NOMINAL = 0;
 *     MODE_SAFE = 1;   // autonomous fallback mode (§4.4: both a mitigation and an attack surface)
 *     MODE_PAYLOAD = 2;
 * }
 * </pre>
 */
enum SatMode {
    MODE_NOMINAL = 0,
    MODE_SAFE = 1,
    MODE_PAYLOAD = 2
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SatMode& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SatMode& e) { int n; b->unpack(n); e = static_cast<SatMode>(n); }

/**
 * Enum generated from <tt>src/LifesatPackets.msg:34</tt> by opp_msgtool.
 * <pre>
 * //
 * // Telecommand classes. A2 (unauthorised command) and A6 (unauthorised update) are
 * // drawn from this set; only nominal ones flow under B0.
 * //
 * enum CommandType
 * {
 *     CMD_NOOP = 0;
 *     CMD_SET_PARAM = 1;
 *     CMD_SET_MODE = 2;
 *     CMD_UPDATE = 3;   // software/configuration update (A6, L1)
 * }
 * </pre>
 */
enum CommandType {
    CMD_NOOP = 0,
    CMD_SET_PARAM = 1,
    CMD_SET_MODE = 2,
    CMD_UPDATE = 3
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CommandType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CommandType& e) { int n; b->unpack(n); e = static_cast<CommandType>(n); }

/**
 * Class generated from <tt>src/LifesatPackets.msg:49</tt> by opp_msgtool.
 * <pre>
 * //
 * // Ground to satellite telecommand.
 * //
 * // sequence and issuedAt carry freshness and D1 checks them: command payloads need a
 * // count or nonce against replay and spoofing. authTag is produced in phase 1 but not
 * // verified under D0.
 * //
 * packet Telecommand
 * {
 *     long commandId;
 *     long sequence;
 *     simtime_t issuedAt;
 *     int commandType \@enum(CommandType) = CMD_NOOP;
 * 
 *     string paramKey = "";
 *     double paramValue = 0;
 *     int targetMode \@enum(SatMode) = MODE_NOMINAL;
 * 
 *     string authTag = "";        // the signature D1 will verify
 *     string payloadDigest = "";  // body digest for the integrity check
 * }
 * </pre>
 */
class Telecommand : public ::omnetpp::cPacket
{
  protected:
    long commandId = 0;
    long sequence = 0;
    ::omnetpp::simtime_t issuedAt = SIMTIME_ZERO;
    int commandType = CMD_NOOP;
    ::omnetpp::opp_string paramKey = "";
    double paramValue = 0;
    int targetMode = MODE_NOMINAL;
    ::omnetpp::opp_string authTag = "";
    ::omnetpp::opp_string payloadDigest = "";

  private:
    void copy(const Telecommand& other);

  protected:
    bool operator==(const Telecommand&) = delete;

  public:
    Telecommand(const char *name=nullptr, short kind=0);
    Telecommand(const Telecommand& other);
    virtual ~Telecommand();
    Telecommand& operator=(const Telecommand& other);
    virtual Telecommand *dup() const override {return new Telecommand(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual long getCommandId() const;
    virtual void setCommandId(long commandId);

    virtual long getSequence() const;
    virtual void setSequence(long sequence);

    virtual ::omnetpp::simtime_t getIssuedAt() const;
    virtual void setIssuedAt(::omnetpp::simtime_t issuedAt);

    virtual int getCommandType() const;
    virtual void setCommandType(int commandType);

    virtual const char * getParamKey() const;
    virtual void setParamKey(const char * paramKey);

    virtual double getParamValue() const;
    virtual void setParamValue(double paramValue);

    virtual int getTargetMode() const;
    virtual void setTargetMode(int targetMode);

    virtual const char * getAuthTag() const;
    virtual void setAuthTag(const char * authTag);

    virtual const char * getPayloadDigest() const;
    virtual void setPayloadDigest(const char * payloadDigest);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Telecommand& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Telecommand& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/LifesatPackets.msg:70</tt> by opp_msgtool.
 * <pre>
 * //
 * // Satellite to ground telemetry, carrying the three state channels (section 5.1).
 * //
 * // These are declared behaviour models, not a validated power or thermal model of a
 * // platform; the limit is stated in L6.
 * //
 * packet Telemetry
 * {
 *     long telemetrySeq;
 *     simtime_t sourceTime;       // instant of generation onboard -- the twin's delay measurement rests on this
 * 
 *     // physical channel
 *     double batteryVoltage;      // V
 *     bool illuminated;           // in sunlight or in eclipse
 * 
 *     // logical channel
 *     int mode \@enum(SatMode) = MODE_NOMINAL;
 *     string paramDigest = "";    // digest of the parameter store
 * 
 *     // security channel
 *     long rejectedCmdCount;      // number of commands D1 rejected (the target of A7c)
 *     long acceptedCmdCount;
 * 
 *     string integrityTag = "";
 * }
 * </pre>
 */
class Telemetry : public ::omnetpp::cPacket
{
  protected:
    long telemetrySeq = 0;
    ::omnetpp::simtime_t sourceTime = SIMTIME_ZERO;
    double batteryVoltage = 0;
    bool illuminated = false;
    int mode = MODE_NOMINAL;
    ::omnetpp::opp_string paramDigest = "";
    long rejectedCmdCount = 0;
    long acceptedCmdCount = 0;
    ::omnetpp::opp_string integrityTag = "";

  private:
    void copy(const Telemetry& other);

  protected:
    bool operator==(const Telemetry&) = delete;

  public:
    Telemetry(const char *name=nullptr, short kind=0);
    Telemetry(const Telemetry& other);
    virtual ~Telemetry();
    Telemetry& operator=(const Telemetry& other);
    virtual Telemetry *dup() const override {return new Telemetry(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual long getTelemetrySeq() const;
    virtual void setTelemetrySeq(long telemetrySeq);

    virtual ::omnetpp::simtime_t getSourceTime() const;
    virtual void setSourceTime(::omnetpp::simtime_t sourceTime);

    virtual double getBatteryVoltage() const;
    virtual void setBatteryVoltage(double batteryVoltage);

    virtual bool getIlluminated() const;
    virtual void setIlluminated(bool illuminated);

    virtual int getMode() const;
    virtual void setMode(int mode);

    virtual const char * getParamDigest() const;
    virtual void setParamDigest(const char * paramDigest);

    virtual long getRejectedCmdCount() const;
    virtual void setRejectedCmdCount(long rejectedCmdCount);

    virtual long getAcceptedCmdCount() const;
    virtual void setAcceptedCmdCount(long acceptedCmdCount);

    virtual const char * getIntegrityTag() const;
    virtual void setIntegrityTag(const char * integrityTag);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Telemetry& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Telemetry& obj) {obj.parsimUnpack(b);}


}  // namespace lifesat


namespace omnetpp {

template<> inline lifesat::Telecommand *fromAnyPtr(any_ptr ptr) { return check_and_cast<lifesat::Telecommand*>(ptr.get<cObject>()); }
template<> inline lifesat::Telemetry *fromAnyPtr(any_ptr ptr) { return check_and_cast<lifesat::Telemetry*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __LIFESAT_LIFESATPACKETS_M_H

