#!/usr/bin/env python3
"""Mutation catalogue for the Task-5 semantic-regression suite.

Each entry names ONE exact symbol in the production scorer, the textual edit that
reintroduces a specific contract violation, and the diagnostic that must fire.
The edits are applied to a THROWAWAY COPY of the scorer; the live tree is never
touched (see run_mutation_suite.py).

`expect_any` lists test names of which at least one must FAIL for the mutant to
count as caught for the intended reason. `expect_gate` names a gate-level check
instead, for mutations that the test suite cannot see (e.g. a forbidden import).
"""

# ---------------------------------------------------------------------------
# Real mutants: every one must turn the gate RED for its intended reason.
# ---------------------------------------------------------------------------
MUTANTS = [
    {
        "id": "M01_replay_identity_from_cmdid",
        "symbol": "scoring/ontology.py::attack_action_id",
        "violates": "INV-01 attack_action_id derived from the immutable truth row",
        "old": '    return "%s#truth:%d" % (run, truth_idx)',
        "new": '    return "%s#cmd" % run          # MUTANT: identity collapses on cmdId',
        "file": "scoring/ontology.py",
        "expect_any": ["test_replay_actions_get_distinct_identities"],
    },
    {
        "id": "M02_original_acceptance_hostile",
        "symbol": "scoring/matching.py::match (monotone lower bound)",
        "violates": "INV-02 the original legitimate acceptance stays benign",
        "old": "                if cand[\"t\"] < a[\"t\"] or cand[\"t\"] >= bound:",
        "new": "                if cand[\"t\"] >= bound:   # MUTANT: claims pre-action events",
        "file": "scoring/matching.py",
        "expect_any": ["test_original_legitimate_acceptance_stays_benign",
                       "test_a3_accepted_replays_split_330_84"],
    },
    {
        "id": "M03_idempotent_counted_as_state_change",
        "symbol": "scoring/state.py::replay_parameter_store",
        "violates": "INV-28 an identical rewrite is accepted_idempotent_no_change",
        "old": "            if prevailing is not None and abs(value - prevailing) < TOLERANCE:\n                verdicts[row[\"idx\"]] = IDEMPOTENT\n            else:\n                verdicts[row[\"idx\"]] = STATE_CHANGED",
        "new": "            verdicts[row[\"idx\"]] = STATE_CHANGED   # MUTANT: no idempotency",
        "file": "scoring/state.py",
        "expect_any": ["test_a3_accepted_replays_split_330_84",
                       "test_idempotent_write_neither_opens_nor_closes"],
    },
    {
        "id": "M04_window_closes_on_legitimate_only",
        "symbol": "scoring/state.py::effect_windows (closing rule)",
        "violates": "INV-32 the window closes on a differing write of EITHER origin",
        "old": "            if abs(written_value(later[\"f\"][\"cmdId\"]) - value) >= TOLERANCE:",
        "new": "            if (later[\"idx\"] not in verdicts\n                    and abs(written_value(later[\"f\"][\"cmdId\"]) - value) >= TOLERANCE):",
        "file": "scoring/state.py",
        "expect_any": ["test_window_closes_on_a_differing_write_of_either_origin",
                       "test_later_hostile_write_with_a_different_value_closes_the_window"],
    },
    {
        "id": "M05_alarm_credits_many_events",
        "symbol": "scoring/state.py::credit_alarms",
        "violates": "INV-23 one alarm credits at most one effect event",
        "old": "            if e[\"start\"] - 1e-9 <= a <= e[\"stop\"] + 1e-9:\n                claimed.add(i)\n                break",
        "new": "            if e[\"start\"] - 1e-9 <= a <= e[\"stop\"] + 1e-9:\n                claimed.add(i)   # MUTANT: no break, one alarm credits many",
        "file": "scoring/state.py",
        "expect_any": ["test_one_alarm_credits_at_most_one_effect_event",
                       "test_single_alarm_overlapping_three_events_credits_one",
                       "test_two_alarms_credit_two_distinct_events"],
    },
    {
        "id": "M06_d2_decision_per_observation",
        "symbol": "scoring/windows.py::decision_set",
        "violates": "INV-03 one D2 decision per non-empty window, not per observation",
        "old": "    opportunities = {observation_window(r[\"t\"]) for r in events\n                     if r[\"cat\"] == \"tm.recv\"}",
        "new": "    opportunities = {r[\"f\"].get(\"seq\") for r in events\n                     if r[\"cat\"] == \"tm.recv\"}   # MUTANT: per observation",
        "file": "scoring/windows.py",
        "expect_any": ["test_one_decision_per_nonempty_window_not_per_observation",
                       "test_corpus_mapping_dedup_585_to_469"],
    },
    {
        "id": "M07_no_window_dedup",
        "symbol": "scoring/families.py::direct_detection_d2 (truth window set)",
        "violates": "INV-29 mappings collapse to unique (run, window) units",
        "old": "    truth_windows = {m[\"window\"] for m in mappings} & opportunities\n    tp = len(truth_windows & alarm_windows)\n    fn = len(truth_windows - alarm_windows)",
        "new": "    truth_list = [m[\"window\"] for m in mappings\n                  if m[\"window\"] in opportunities]   # MUTANT: no dedup\n    truth_windows = set(truth_list)\n    tp = sum(1 for w in truth_list if w in alarm_windows)\n    fn = sum(1 for w in truth_list if w not in alarm_windows)",
        "file": "scoring/families.py",
        "expect_any": ["test_one_decision_per_nonempty_window_not_per_observation",
                       "test_corpus_mapping_dedup_585_to_469"],
        "expect_marker": "D2 decision replicated",
    },
    {
        "id": "M08_drop_removed_from_accounting",
        "symbol": "scoring/families.py::action_accounting (drop disposition)",
        "violates": "INV-04 every A4 action reconciles to exactly one disposition",
        "old": "        elif a[\"action\"] == \"drop_telemetry\":\n            key = (\"dropped\" if seq in sent and seq not in received else \"unresolved\")",
        "new": "        elif a[\"action\"] == \"drop_telemetry\":\n            continue   # MUTANT: drops vanish from the denominator",
        "file": "scoring/families.py",
        "expect_any": ["test_every_action_lands_in_exactly_one_disposition",
                       "test_drops_are_not_silently_removed_from_the_denominator"],
    },
    {
        "id": "M09_prevention_as_state_effect",
        "symbol": "scoring/state.py::spacecraft_effect",
        "violates": "INV-05/INV-24 prevention is never a state transition",
        "old": "    if record[\"outcome\"] == \"rejected\":\n        return PREVENTED",
        "new": "    if record[\"outcome\"] == \"rejected\":\n        return STATE_CHANGED   # MUTANT: prevention scored as effect",
        "file": "scoring/state.py",
        "expect_any": ["test_prevention_is_not_a_state_effect",
                       "test_original_legitimate_acceptance_stays_benign"],
    },
    {
        "id": "M10_f4_observed_transition_denominator",
        "symbol": "scoring/families.py::secondary_reporting (denominator basis)",
        "violates": "INV-19 the denominator is the evidence event, not a transition",
        "old": "    rejections = sorted(r[\"outcome_t\"] for r in command_records\n                        if r[\"outcome\"] == \"rejected\")\n    observations = _observations_with_counter(events)",
        "new": "    observations = _observations_with_counter(events)\n    # MUTANT: the denominator is rebuilt from OBSERVED counter transitions, so a\n    # unit exists only where reporting already happened (circular).\n    rejections = []\n    _prev = None\n    for _o in observations:\n        if _o[\"rej\"] is None:\n            continue\n        if _prev is not None and _o[\"rej\"] != _prev:\n            rejections.append(_o[\"src\"] - 1e-9)\n        _prev = _o[\"rej\"]",
        "file": "scoring/families.py",
        "expect_any": ["test_3_unchanged_counter_with_alarm_is_unresolved_never_reported",
                       "test_5_two_rejections_but_only_one_increment_is_fail_closed",
                       "test_9_no_eligible_observation_is_no_reporting_opportunity"],
        "expect_marker": "unresolved",
    },
    {
        "id": "M11_f4_arrival_time_eligibility",
        "symbol": "scoring/families.py::_observations_with_counter (source time)",
        "violates": "INV-20 eligibility runs on telemetry source time",
        "old": "                     \"src\": telemetry_source_time(row), \"rej\": counter,",
        "new": "                     \"src\": row[\"t\"], \"rej\": counter,   # MUTANT: arrival time",
        "file": "scoring/families.py",
        "expect_any": ["test_inflight_observation_is_not_the_reporting_opportunity",
                       "test_10_inflight_observation_is_not_eligible",
                       "test_corpus_is_1302_reported_0_not_reported"],
    },
    {
        "id": "M12_f4_channel_filter",
        "symbol": "scoring/families.py::secondary_reporting (alarm set)",
        "violates": "INV-16 the numerator is not filtered on the channel label",
        "old": "    alarm_seqs = {r[\"f\"].get(\"tmSeq\") for r in events if r[\"cat\"] == \"d3.alarm\"}\n\n    counts = {\"reported\": 0",
        "new": "    alarm_seqs = {r[\"f\"].get(\"tmSeq\") for r in events\n                  if r[\"cat\"] == \"d3.alarm\"\n                  and r[\"f\"].get(\"channel\") == \"security\"}   # MUTANT\n\n    counts = {\"reported\": 0",
        "file": "scoring/families.py",
        "expect_any": ["test_numerator_is_not_filtered_on_the_channel_label",
                       "test_corpus_is_1302_reported_0_not_reported"],
    },
    {
        "id": "M13_f4_no_counter_verification",
        "symbol": "scoring/families.py::secondary_reporting (increment check)",
        "violates": "f4_semantics counter verification; an unexplained alarm reports",
        "old": "        if observation[\"rej\"] != expected_absolute:",
        "new": "        if False:   # MUTANT: counter read but never verified",
        "file": "scoring/families.py",
        "expect_any": ["test_3_unchanged_counter_with_alarm_is_unresolved_never_reported",
                       "test_5_two_rejections_but_only_one_increment_is_fail_closed",
                       "test_8_decreasing_counter_is_unresolved"],
    },
    {
        "id": "M14_f4_relative_baseline_reanchor",
        "symbol": "scoring/families.py::secondary_reporting (absolute expectation)",
        "violates": "a broken chain must never re-anchor the expectation",
        "old": "        preceding = sum(1 for t in rejections if t < observation[\"src\"])\n        expected_absolute = baseline + preceding",
        "new": "        prior = [o for o in observations[:position] if o[\"rej\"] is not None]\n        expected_absolute = ((prior[-1][\"rej\"] if prior else baseline)\n                             + len(members))   # MUTANT: relative re-anchor",
        "file": "scoring/families.py",
        "expect_any": ["test_12_broken_chain_does_not_re_anchor",
                       "test_13_catch_up_observation_is_classified_by_its_own_first_eligible"],
    },
    {
        "id": "M15_undefined_coerced_to_zero",
        "symbol": "scoring/metrics.py::ratio",
        "violates": "INV-06 an undefined ratio is null with a reason code",
        "old": "    if denominator == 0:\n        return None, zero_code",
        "new": "    if denominator == 0:\n        return 0.0, None   # MUTANT: coercion to 0.0",
        "file": "scoring/metrics.py",
        "expect_any": ["test_undefined_ratios_are_not_coerced_to_zero"],
    },
    {
        "id": "M16_macro_and_pooled_merged",
        "symbol": "scoring/output.py::estimand_result (separate fields)",
        "violates": "INV-07 macro and pooled occupy different named fields",
        "old": '            "macro_mean_over_defined_runs": macro, "pooled_ratio": pooled_value,',
        "new": '            "macro_mean_over_defined_runs": pooled_value,\n            "pooled_ratio": pooled_value,   # MUTANT: one estimand under two names',
        "file": "scoring/output.py",
        "expect_any": ["test_macro_and_pooled_are_separate_named_fields",
                       "test_all_zero_cell_reports_counts_not_a_zero_interval",
                       "test_unequal_run_weights_give_different_macro_and_pooled"],
    },
    {
        "id": "M17_bootstrap_unit_observation",
        "symbol": "scoring/output.py::RESAMPLING_UNIT",
        "violates": "uncertainty.resampling_unit is the seven-day run, not the observation",
        "old": 'RESAMPLING_UNIT = "run"',
        "new": 'RESAMPLING_UNIT = "observation"   # MUTANT: wrong resampling unit',
        "file": "scoring/output.py",
        "expect_any": ["test_ci_unit_is_the_run_not_the_observation"],
        "expect_marker": "CONTRACT CI-UNIT VIOLATION",
    },
    {
        "id": "M20_ci_scope_suppressed_cell_wide",
        "symbol": "scoring/output.py::estimand_is_all_zero",
        "violates": "the zero-event rule is scoped to the estimand, not the cell",
        "old": "    defined = [p.get(\"value\") for p in per_run or [] if p.get(\"value\") is not None]\n    return bool(defined) and all(v == 0.0 for v in defined)",
        "new": "    defined = [p.get(\"value\") for p in per_run or [] if p.get(\"value\") is not None]\n    # MUTANT: any zero run suppresses the whole estimand's interval, which is\n    # how a cell-wide rule behaves once a sibling estimand is uniformly zero.\n    return bool(defined) and any(v == 0.0 for v in defined)",
        "file": "scoring/output.py",
        "expect_any": ["test_mixed_cell_zero_estimand_does_not_delete_the_other_interval"],
        "expect_marker": "CONTRACT CI-SCOPE VIOLATION",
    },
    {
        "id": "M18_output_schema_drops_per_run",
        "symbol": "scoring/output.py::estimand_result (per_run records)",
        "violates": "INV-31 per-run records are mandatory",
        "old": '            "per_run": per_run}',
        "new": '            }   # MUTANT: per_run removed',
        "file": "scoring/output.py",
        "expect_any": ["test_per_run_records_are_present_for_every_run"],
    },
    {
        "id": "M19_production_imports_oracle",
        "symbol": "score.py::module imports",
        "violates": "production code may not import the test oracle or reference scorer",
        "old": "from scoring import artefacts, families, matching, ontology, output, state  # noqa: E402",
        "new": "from scoring import artefacts, families, matching, ontology, output, state  # noqa: E402\nimport contract_oracle   # MUTANT: production imports the test oracle",
        "file": "score.py",
        "expect_gate": "forbidden_oracle_imports",
    },
]

# ---------------------------------------------------------------------------
# Negative controls: the gate must stay GREEN.
# ---------------------------------------------------------------------------
NEGATIVE_CONTROLS = [
    {
        "id": "NC1_comment_and_whitespace_only",
        "symbol": "scoring/metrics.py::ratio (comment above the body)",
        "file": "scoring/metrics.py",
        "old": '    """A zero denominator yields null plus a reason code, never 0.0."""',
        "new": '    """A zero denominator yields null plus a reason code, never 0.0."""\n    # NEGATIVE CONTROL: a comment changes no behaviour.\n',
    },
    {
        "id": "NC2_semantically_equivalent_refactor",
        "symbol": "scoring/metrics.py::macro_over_defined_runs (loop vs comprehension)",
        "file": "scoring/metrics.py",
        "old": "    defined = [v for v in values if v is not None]",
        "new": "    defined = []\n    for _v in values:            # NEGATIVE CONTROL: same result, other shape\n        if _v is not None:\n            defined.append(_v)",
    },
    {
        "id": "NC3_reference_test_assets_present",
        "symbol": "(no production edit; the test-only reference files are present)",
        "file": None, "old": None, "new": None,
    },
    {
        "id": "NC4_unmodified_scorer",
        "symbol": "(no edit at all; contract hashes and raw artefacts untouched)",
        "file": None, "old": None, "new": None,
    },
]
